name: Unit Tests Run
on: 
  pull_request:
    branches:
      - '**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Java 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'
            
            - name: Print test file
              run: cat src/test/java/io/github/isagroup/PricingEvaluatorUtilTests.java

            - name: Build with Maven
              run: mvn test

            